version: 0.2 
phases:
  install:
    runtime-versions:
        nodejs: 10
artifacts:
  type: zip
  files:
    - README.md
    - package.json
    - app.js
    - .ebextensions/*
    - node_modules/**/*
    - public/**/*
