version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 10.16.0
  pre_build:
    commands:
      - npm install  
artifacts:
  type: zip
  files:
    - README.md
    - package.json
    - app.js
    - .ebextensions/*
    - node_modules/**/*
    - public/**/*
